# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://semiformal.net
title: SemiFormal.net
email: admin@semiformal.net
author: Admin
description: > # "Write an awesome description for your new site here. 
  Landing page for semiformal.net
copyright:
credits: 'Credits: Jekyll template from github.com/swcool'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/semiformal-net
  - title: linkedin
    url: https://www.linkedin.com/in/paul-edwards-to/
